default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', '') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', '') %>

development:
  <<: *default
  database: novato_development

test:
  <<: *default
  database: novato_test
  url: <%= ENV.fetch('DATABASE_URL', '') %>

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
